name: action_manager_poc
description: A Flutter clean architecture project BLoC.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #icon
  ionicons: ^0.2.2

  #state management
  flutter_bloc: ^8.1.2

  #comparing dart objects
  equatable: ^2.0.5

  #service locator
  get_it: ^7.6.0
  
  #dateFormat
  intl: ^0.18.1

  #Database
  floor: any

  #make request to api
  retrofit: ^4.0.3

  #Hooks
  flutter_hooks: ^0.20.3

  #chached image 
  cached_network_image: ^3.2.0

  #data table
  data_table_2: ^2.5.8

  json_annotation: ^4.7.0  

  sqflite_common_ffi: ^2.2.5
  freezed_annotation: ^2.4.1

  go_router: ^9.0.0

  flutter_adaptive_scaffold: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  retrofit_generator: ^8.0.1
  floor_generator: ^1.4.2
  build_runner: ^2.3.1
  json_serializable: ^6.5.4
  freezed: ^2.2.0
  

flutter:

  uses-material-design: true

 
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300