import '../features/app/domain/entities/oso/oso.dart';

const oso_zoznam_dummy = [
  OsoEntity(
      id: 1,
      meno: "Marek",
      priezvisko: "Vopršálek",
      titul: "ING",
      telefon: "0901999888",
      datumNarodenia: "5.5.1955",
      miestoNarodenia: "Šala",
      bydlisko: "Sereď",
      pek: "1001",
      cisloPeciatky: "1001/001",
      platnostOsvedceniaDatum: "2025/03/31",
      zostavajuceDniPlatnosti: null),
  OsoEntity(
      id: 2,
      meno: "Juraj",
      priezvisko: "Mokrý",
      titul: "ING",
      telefon: "0901222123",
      datumNarodenia: "7.7.1977",
      miestoNarodenia: "Žilina",
      bydlisko: "Žilina",
      pek: null,
      cisloPeciatky: null,
      platnostOsvedceniaDatum: null,
      zostavajuceDniPlatnosti: null),
  OsoEntity(
      id: 3,
      meno: "Michal",
      priezvisko: "Molotov",
      titul: "BC",
      telefon: "0901222123",
      datumNarodenia: "11.8.1957",
      miestoNarodenia: "Sniná",
      bydlisko: "Sereď",
      pek: "1001",
      cisloPeciatky: "1001/003",
      platnostOsvedceniaDatum: "2024/06/30",
      zostavajuceDniPlatnosti: null),
  OsoEntity(
      id: 4,
      meno: "Patrik",
      priezvisko: "Podokvap",
      titul: "ING",
      telefon: "09051687321",
      datumNarodenia: "13.10.1982",
      miestoNarodenia: "Modra",
      bydlisko: "Bratislava",
      pek: "1002",
      cisloPeciatky: "1002/004",
      platnostOsvedceniaDatum: "2024/06/30",
      zostavajuceDniPlatnosti: null),
];
